# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        overwrite-settings: false
        server-id: Java
        server-username: jjohanning0798
        server-password: ${{ secrets.AZDO_TOKEN }}
        # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        # settings-path: ${{ github.workspace }} # location for the settings.xml file
    - run: cat settings.xml
    - run: mvn help:effective-settings # -s settings.xml
    # - run: mvn install --file pom.xml -s settings.xml
    #   env:
    #     AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml -s settings.xml
      env:
        AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
