# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    # OPTION 1 - use setup java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: Java
        server-username: jjohanning0798
        server-password: ${{ secrets.AZDO_TOKEN }}

    - run: mvn help:effective-settings # -s settings.xml

    # OPTION 2: specify a settings.xml and use ${env.VARIABLES} in the file
    # - run: mvn install --file pom.xml -s settings.xml
    #   env:
    #     AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml -s settings.xml
      env:
        AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
